version: 0.7.{build}



os: Visual Studio 2017

configuration: Release



environment:

  matrix:

    - compiler: msvc-15-seh

      build_system: cmake

      CMAKE_GENERATOR: Visual Studio 15 2017 Win64

      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

      MSVC_PLATFORM: amd64

      BITS: 64



    - compiler: msvc-15-seh

      build_system: cmake

      CMAKE_GENERATOR: Visual Studio 15 2017

      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

      MSVC_PLATFORM: x86

      BITS: 32






before_build:

  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars%BITS%.bat"

  - md package

  - md build

  - cd build 

  - cmake ../src -DCMAKE_INSTALL_PREFIX=.




build_script:

  - cmake --build . 

  - cmake --build . --target install



after_build:

   - cd ../package

   - copy "%APPVEYOR_BUILD_FOLDER%\deps\bin\*.dll" "bin\"

   - 7z a ../huc.zip * -tzip

   

artifacts:

  - path: huc.zip

    name: huc-v${appveyor_build_version}-%MSVC_PLATFORM%.zip
